### ISSUE TITLE
applepay fix for configurable products / products with options

### ISSUE THREAD

**Issue by wmwnuk** [mollie/magento2-hyva-compatibility#15]
Currently it is not possible to buy a configurable product with apple pay button on product page. The problem is that none of the product options are passed to buyNowValidation action, so the product is not added to cart.

**Comment by Frank-Magmodules** [comment]
Hello @wmwnuk, as we discussed this on Slack with your team, we've incorporated some logic of your [PR](https://github.com/mollie/magento2-hyva-compatibility/pull/14) into our [latest release](https://github.com/mollie/magento2-hyva-compatibility/releases). We appreciate you bringing this to our attention and sharing a potential fix with us.

I'm closing this issue for now, but please feel free to reopen it if necessary.
