### ISSUE TITLE
Empty cart on browser history back

### ISSUE THREAD

**Issue by mvenghaus** [mollie/magento2-hyva-compatibility#4]
Hey,

after the ordering i'm landing on the mollie hosted payment page. But when I click back in the Browser the cart is empty. It's little bit of a conversion killer ;)

A solution could be to set a session variable before going to mollie and when i'm coming back to the shop and it is not success page then restore the cart from order!?

Regards
MArcus

**Comment by Frank-Magmodules** [comment]
Hi there @mvenghaus , thanks for clearly outlining the problem. 
We'll try to reproduce it and address it in the upcoming release. Thanks for your patience!

**Comment by Frank-Magmodules** [comment]
Hi @mvenghaus, we've identified this issue with the Mollie payment plugin. A new release is scheduled for later this week, which should resolve this problem. I'll keep this issue open until it's confirmed. Thank you for your patience.

**Comment by Frank-Magmodules** [comment]
As you may have noticed, we have resolved the problem in the payment module starting from version [2.26.0](https://github.com/mollie/magento2/releases). Therefore, I am closing this issue for the time being. We appreciate your patience!
