### ISSUE TITLE
Apple Pay button shows old 'Place Order' text inside of the button

### ISSUE THREAD

**Issue by jesse-deboer** [mollie/magento2-hyva-compatibility#5]
When you use the direct mode of Apple Pay the `Place Order` text from inside the button is still visible 'behind' the button of Apple Pay.

Should be fixed like this: https://github.com/mollie/magento2-hyva-compatibility/pull/6

**Comment by Frank-Magmodules** [comment]
Hi @jesse-deboer , thanks for your PR and for raising this issue. We'll review it along with your pull request and merge it in our upcoming release. Appreciate your patience and contribution!

**Comment by jesse-deboer** [comment]
Hi @Frank-Magmodules, will be working on this project tomorrow and let you know what was going wrong. It could indeed be some custom CSS overwriting the value.

**Comment by Frank-Magmodules** [comment]
Sure @jesse-deboer , let me know!

**Comment by jesse-deboer** [comment]
Closed the PR, it was indeed a custom value. Maybe adding a important tag would help with this?

https://github.com/mollie/magento2-hyva-compatibility/pull/10

**Comment by Frank-Magmodules** [comment]
Thanks @jesse-deboer , surely we can do that! We will add it to the next release.

**Comment by Frank-Magmodules** [comment]
Hi There @jesse-deboer , Apologies for the delayed response. The solution has already been incorporated into the release. Please see the specific commit where we included the "!important" [here](https://github.com/mollie/magento2-hyva-checkout/blob/main/src/Mollie_HyvaCheckout/view/frontend/tailwind/tailwind-source.css#L26
).
