### ISSUE TITLE
Browser error after entering test CC details and pressing Enter

### ISSUE THREAD

**Issue by Vinai** [mollie/magento2-hyva-compatibility#8]
I’ve configured mollie in test mode on my local dev instance.  

After entering [test CC details](https://docs.mollie.com/overview/testing) and I hit Enter, the following error is logged in the browser console: `Components need to be mounted inside of a <form> tag`.

![Bildschirmfoto 2023-06-05 um 15 38 01](https://github.com/mollie/magento2-hyva-compatibility/assets/72463/3f79dde8-46ef-4ca4-af39-c93ae0876abe)

Placing the order still works - the error does not interfere.

Version:
```
% composer show mollie/magento2-hyva-compatibility                                      
name     : mollie/magento2-hyva-compatibility
descrip. : Hyvä Themes Compatibility module for Mollie Payments
keywords : 
versions : * 1.0.2
```

**Comment by Frank-Magmodules** [comment]
We also had a discussion on Slack with @Vinai, but we appreciate you bringing up this issue here too. We will make an effort to reproduce it and provide a prompt response at your earliest convenience.

**Comment by Vinai** [comment]
Thank you 🙌

**Comment by Frank-Magmodules** [comment]
Greetings @Vinai,

I'm delighted to share with you that the issue has been successfully resolved and has already been included in the release, although I regret not notifying you earlier about it. You can locate the exact commit [here](https://github.com/mollie/magento2-hyva-checkout/commit/18364247c885291a30bbbeee7ecf6f1a746a3c6c). I'll be closing this matter for the time being, but please feel free to reopen it should the need arise.

**Comment by Vinai** [comment]
Thank you! 👍🏻🎉🙏🏻
